version: '3.8'

services:
  mariadb:
    image: mariadb
    container_name: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: debezium
      MARIADB_DATABASE: change_data_capture
      MARIADB_USER: mariauser
      MARIADB_PASSWORD: mariapw
    ports:
      - "3307:3306"
    volumes:
      - "./mariadb_init.sql:/docker-entrypoint-initdb.d/1.sql"

  postgres:
    image: quay.io/debezium/postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: change_data_capture
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5433:5432"
    volumes:
      - "./postgresql.conf:/etc/postgresql/postgresql.conf"
      - "./postgres_init.sql:/docker-entrypoint-initdb.d/10-init.sql"

  zookeeper:
    image: quay.io/debezium/zookeeper:2.7
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"

  kafka:
    image: quay.io/debezium/kafka:2.7
    ports:
      - "9092:9092"
    links:
      - zookeeper
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181

  connect:
    image: quay.io/debezium/connect:2.7
    ports:
      - "8083:8083"
    links:
      - kafka
      - mariadb
      - postgres
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses
      - CONNECT_REST_ADVERTISED_HOST_NAME=connect

  microservice:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - kafka
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_MARIADB_URL=mysql+pymysql://cdc_user:password@mariadb:3306/mydb
      - DATABASE_POSTGRES_URL=postgresql://user:password@postgres:5432/mydb

volumes:
  mariadb_data:
  postgres_data:
